### ISSUE TITLE
请求支持ob的callouts格式

### ISSUE THREAD

**Issue by taklele** [sunbooshi/note-to-mp#13]
https://help.obsidian.md/Editing+and+formatting/Callouts

谢谢大佬。

**Comment by Moyf** [comment]
附议~
以及如果实现了的话，能否也考虑添加对 Admonition 插件（https://github.com/javalent/admonitions ）的支持？
![image](https://github.com/sunbooshi/note-to-mp/assets/4013062/7116c3f8-a5b2-4c5e-8aba-b5acc7ed7914)

这是一个下载量 63W 的插件，用代码块的方式实现了类似 Callout 的功能（在官方推出之前基本都是靠它实现的），
在现在仍然有很大的优势来作为 Callout 使用。

**Comment by sunbooshi** [comment]
> 附议~ 以及如果实现了的话，能否也考虑添加对 Admonition 插件（https://github.com/javalent/admonitions ）的支持？ ![image](https://private-user-images.githubusercontent.com/4013062/328422547-7116c3f8-a5b2-4c5e-8aba-b5acc7ed7914.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjY4MzksIm5iZiI6MTcxNTA2NjUzOSwicGF0aCI6Ii80MDEzMDYyLzMyODQyMjU0Ny03MTE2YzNmOC1hNWIyLTRjNWUtOGFiYS1iNWFjYzdlZDc5MTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDdUMDcyMjE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWZmMTU5NzdlN2JmMzliODI1ZjRlNmQ2ODE5MzU2NDE5ZWQwMmVkN2Q2ZTkyZWEzMTE1OTEzYWVjMjU0M2Q2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.IsYXiaHEy9UO7Yei_imLEftWbIMD-Q8bZgkV5_9yEec)
> 
> 这是一个下载量 63W 的插件，用代码块的方式实现了类似 Callout 的功能（在官方推出之前基本都是靠它实现的）， 在现在仍然有很大的优势来作为 Callout 使用。

这个我考虑一下吧。跟代码块搞在一起的话处理上会比较麻烦一些，现在代码的处理用的是第三方的插件。

**Comment by Moyf** [comment]
好像不适配暗色模式的主题：
![image](https://github.com/sunbooshi/note-to-mp/assets/4013062/d74e1067-d2ee-42be-bd7a-52096641fd51)

![image](https://github.com/sunbooshi/note-to-mp/assets/4013062/2db4c492-e24d-47b2-803c-990b9c0d6bff)
而且会有一个 `undefined` 文本……（图标？

**Comment by sunbooshi** [comment]
现在样式是写死的。
undefined那个可能是不支持的图标，你把原始的内容发一下我看看。

**Comment by Moyf** [comment]
> 现在样式是写死的。 undefined那个可能是不支持的图标，你把原始的内容发一下我看看。

> [!Warning] 自己的跑测
> 每个周三要自己跑测一下

![image](https://github.com/sunbooshi/note-to-mp/assets/4013062/4e7235ff-30cf-47e7-9279-c5e06dfea818)
图标是 lucide 的 warn （我没印象自己单独设置过，应该是默认的？

建议如果是不支持的话，直接不显示图标，会比多一个 `undefined` 更好

___

样式能从主题上继承吗？这些主题应该也有自己的普通 Callout 样式？ 🤔
（或者文字颜色可以使用主题定义的 text color，可以避免暗色模式下的问题

**Comment by sunbooshi** [comment]
[!warning] 自己的跑测
