### ISSUE TITLE
FR：增加「无图片复制」的功能支持

### ISSUE THREAD

**Issue by Moyf** [sunbooshi/note-to-mp#16]
众所都周知，微信公众号是没法混合粘贴图文的。
如果用图床的话还好，但是本地图片的话，粘贴过去之后还得手动把原来的图片链接逐一删除，然后自己粘贴图片过去。

基于此，能否在现在 **复制** 按钮的基础上，添加一个 **复制（无图片）** 的按钮？
——在复制的时候自动去掉所有的 `![](xx.png)` 或者 `![[ooo.jpg]]` 之类的内嵌图片链接，方便在公众号里可以直接粘贴图片

**Comment by sunbooshi** [comment]
这个其实是故意保留的，方便在公众号编辑器里定位缺失的图片。不然图片多了的话找起来还比较麻烦。

**Comment by sunbooshi** [comment]
本地图片现在可以直接上传了
