### ISSUE TITLE
问题反馈：格式缩进

### ISSUE THREAD

**Issue by David-19940718** [sunbooshi/note-to-mp#17]
您好，非常感谢您的开源工作。

现在我这边在 obsidian 用这个插件时可以直接渲染显示也正常，可是尝试复制到公众号编辑页面后，发现都会整体向右缩进，请问有什么解决方案吗？

![image](https://github.com/sunbooshi/note-to-mp/assets/38575158/d3905d04-dce6-4bf6-a51c-f48f76cdd432)

![image](https://github.com/sunbooshi/note-to-mp/assets/38575158/27b96131-bb31-4992-9a4e-0ada4dfa40a4)

**Comment by sunbooshi** [comment]
这个默认主题带了居中。你换一个试试。下一版我去掉吧，这个居中感觉没啥用。微信本身就给居中了。
