### ISSUE TITLE
FR: 过滤obsidian的markdown注释

### ISSUE THREAD

**Issue by ifeitao** [sunbooshi/note-to-mp#19]
建议对型如 `%%[🖋 Edit in Excalidraw](%E6%9C%AA%E5%91%BD%E5%90%8D%201%202024-05-29%2020.41.14.excalidraw.md)%%`  的markdown注释，在复制时可以过滤掉。这样能很好的配合Excalidraw插件。

语法参考：https://publish.obsidian.md/hub/04+-+Guides%2C+Workflows%2C+%26+Courses/Guides/Markdown+Syntax#Obsidian's+Custom+markdown+syntax

**Comment by sunbooshi** [comment]
能不能在附上一个示例文档我看看，最后能截个图，我还是没太理解使用场景。
