### ISSUE TITLE
在编辑器里点击保存，heading的颜色消失

### ISSUE THREAD

**Issue by MarkYang1030** [sunbooshi/note-to-mp#21]
复制过去微信公众号一切正常，但是一点击保存，heading的样式就会变，最直接的是颜色没有了。
请问应该怎么整，谢谢

**Comment by sunbooshi** [comment]
截个图我看一下，这个可能是样式的问题。截一下obsidian中的效果和微信编缉器里的效果。

**Comment by sunbooshi** [comment]
我今天复现了，应该是近期公众号编辑器更新引起的。。。等新版吧。
