### ISSUE TITLE
callout 问题

### ISSUE THREAD

**Issue by clippinglee** [sunbooshi/note-to-mp#26]
1，callout 里面增加list，会向右对齐
2，callout 名称区别大小写，obsidian支持不区分大小写
3，callout 任意名称，obsidian 默认是note，插件显示为undefine
4，本地图片无法直接显示出来，有没有办法显示？
5，callout模式下，如果文字中有'x'识别为代码，整个排序就错乱了

**Comment by sunbooshi** [comment]
用最新的版本试试。
