### ISSUE TITLE
字体颜色，是否可以同步复制粘贴

### ISSUE THREAD

**Issue by Lawson332-eng** [sunbooshi/note-to-mp#27]
遇到的问题：

在obsidian中字体已经设置好了颜色，但复制到公众号后，颜色还是变为黑色字体。
是哪里没有设定好，还是插件本身暂时没有支持。

ps：插件功能确实挺赞👍

![1](https://github.com/sunbooshi/note-to-mp/assets/84008849/0c50af90-b541-41c4-b616-e33e865e76c4)
![2](https://github.com/sunbooshi/note-to-mp/assets/84008849/1851e78c-6a3e-46f7-b69b-1877a4e6d8da)

**Comment by sunbooshi** [comment]
这是Obsidian中的设置的颜色，无法带到插件，可以尝试用插件的自定义CSS把颜色再定义一下。

**Comment by sunbooshi** [comment]
自定义css看这篇教程：https://mp.weixin.qq.com/s/_HQhks2djrIwiMwWBFk6qQ
