### ISSUE TITLE
themes.json解析失败

### ISSUE THREAD

**Issue by jianhekang** [sunbooshi/note-to-mp#7]
您好。感谢无私分享插件。
在启用插件时有个提示，在选择样式时，预览样式也不会变化。
谢谢。
![themes json解析失败](https://github.com/sunbooshi/note-to-mp/assets/165437708/fa893483-b434-4a79-a3dc-478849a2696f)

**Comment by sunbooshi** [comment]
你是不是自己增加样式了？如果是的话，检查一下themes.json的格式对不对。

如果没有增加，那看一下插件目录下有没有themes.json，还得注意现在在插件里themes.json的路径是写死的，一定得是`.obsidian/plugins/note-to-mp/themes.json`，也就是说插件的目录名一定要是`note-to-mp`才行。

**Comment by jianhekang** [comment]
> 你是不是自己增加样式了？如果是的话，检查一下themes.json的格式对不对。
> 
> 如果没有增加，那看一下插件目录下有没有themes.json，还得注意现在在插件里themes.json的路径是写死的，一定得是`.obsidian/plugins/note-to-mp/themes.json`，也就是说插件的目录名一定要是`note-to-mp`才行。

非常感谢，报错的问题解决了。该插件目前不能将图片一起复制到公众号编辑器哈？只是将图片的OB路径复制了过去。

**Comment by sunbooshi** [comment]
图片这个暂时不能，详情看这里 https://github.com/sunbooshi/note-to-mp/issues/8
目前最好的解决方案就是使用图床。

**Comment by jianhekang** [comment]
收到。谢谢您的回复。
