### ISSUE TITLE
笔记中图片显示的问题

### ISSUE THREAD

**Issue by Daniel-J123** [sunbooshi/note-to-mp#8]
作者您好，笔记中的图片可以直接复制显示到公众号吗？可不可以增加该功能，毕竟有的技术文章也需要用图表来佐证。谢谢啦

**Comment by sunbooshi** [comment]
如果是本地图片是不能直接复制到公众号的。如果有大量的图片需要展示的话，建议是利用现成的图床插件，配合图床来实现在公众号展示。

这个功能不适合在本插件实现，因为现在公众号没有提供公开的上传图片的接口，如果要实现这个功能就得用图床，那还不如直接用现成的图床插件了。

**Comment by sunbooshi** [comment]
关于图床的使用可以看看这个视频 https://www.bilibili.com/video/BV1pB4y1n7gM/

不过需要注意的是用图床也会有一点的风险，可能存在被盗链，产生很大的流量。使用图床还是需要一些专业知识的。

所以更不能在本插件里实现这个功能了，容易让用户误会是插件带来的问题。

**Comment by Daniel-J123** [comment]
好的谢谢您的回复和建议，我大概理解了。不过这个插件能够迁移笔记的格式已经很棒了，不然老是会自己重新排版。
