### ISSUE TITLE
Latex公式不支持吗

### ISSUE THREAD

**Issue by merlin02306** [sunbooshi/note-to-mp#9]
$x$这个语法貌似不支持，显示还是$x$。

**Comment by sunbooshi** [comment]
现在还不支持公式，调研一下看看这个容易支持不，可以加一下。

**Comment by sunbooshi** [comment]
1.0.7已支持

**Comment by xiong-ZH-zq** [comment]
1.0.8 版本仍无法支持 LaTeX 公式显示，显示出来仍然是文字内容.

![图片](https://github.com/user-attachments/assets/596df414-f4c9-4d7c-9cc2-94a935da23b4)
